# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: fenfenlehe
  host: demo_db_1
  port: 3306

development:
  <<: *default
  database: ruby_test2

test:
  <<: *default
  database: ruby_test2

production:
  <<: *default
  database: ruby_test2
