# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83846091bf7affc020f8e8c0a082bb2094d95e7d1dcf1f73ccb4b7f31a1ca7502c8368755f9a18c6af13645dcaecad4803f6b2e824d5f832a8c13b5f42d546b0

test:
  secret_key_base: 4e39566527f942ac2001cc945548b48331751010163d2f903c24f07722af7a0201b8aacbe6d5d7057c2be6a2e0546e0bcd5e3108397c4663ca070419a6b8b7d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
